import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'auth.discord.connect': 'Connect with Discord',
        'auth.discord.connected': 'Successfully connected with Discord',
        'auth.login.title': 'Login',
        'auth.login.button': 'Sign In',
        'auth.register.title': 'Register',
        'auth.register.button': 'Create Account',
        'auth.email': 'Email Address',
        'auth.password': 'Password',
        'auth.confirmPassword': 'Confirm Password',
        'auth.remember': 'Stay signed in',
        'auth.forgotPassword': 'Forgot password?',
        'auth.loading': 'Please wait...',
        'auth.span.new.user': 'New here? Create your account',
        'auth.span.existing.user': 'Already have an account? Log in',
        'auth.footer.version': 'Version',
        'auth.error.missingFields': 'Please fill out all fields.',
        'auth.error.invalidLogin': 'Email or password is incorrect.',
        'auth.error.invalidRegister': 'Registration failed.',
        'auth.error.passwordMismatch': 'Passwords do not match.',
        'auth.error.sessionKey': 'Invalid session key.',
        'auth.kick.sessionKey': 'Invalid session – please reconnect.',
        'auth.kick.discord': 'Not in Discord or not whitelisted.',
        'auth.kick.alreadyLoggedIn': 'You are already logged in.',
    },
    de: {
        'auth.discord.connect': 'Mit Discord verbinden',
        'auth.discord.connected': 'Erfolgreich mit Discord verbunden',
        'auth.login.title': 'Anmeldung',
        'auth.login.button': 'Einloggen',
        'auth.register.title': 'Registrierung',
        'auth.register.button': 'Konto erstellen',
        'auth.email': 'E-Mail-Adresse',
        'auth.password': 'Passwort',
        'auth.confirmPassword': 'Passwort bestätigen',
        'auth.remember': 'Angemeldet bleiben',
        'auth.forgotPassword': 'Passwort vergessen?',
        'auth.loading': 'Bitte warten...',
        'auth.span.new.user': 'Neu hier? Konto erstellen',
        'auth.span.existing.user': 'Schon registriert? Jetzt einloggen',
        'auth.footer.version': 'Version',
        'auth.error.missingFields': 'Bitte alle Felder ausfüllen.',
        'auth.error.invalidLogin': 'E-Mail oder Passwort ist falsch.',
        'auth.error.invalidRegister': 'Registrierung fehlgeschlagen.',
        'auth.error.passwordMismatch': 'Passwörter stimmen nicht überein.',
        'auth.error.sessionKey': 'Ungültiger Sitzungsschlüssel.',
        'auth.kick.sessionKey': 'Ungültige Sitzung – bitte erneut verbinden.',
        'auth.kick.discord.notOnServer': 'Nicht auf dem Discord-Server.',
        'auth.kick.discord.noRole': 'Keine Freigabe / Whitelist fehlt.',
        'auth.kick.alreadyLoggedIn': 'Du bist bereits eingeloggt.',
    },
});
