import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'auth.login.title': 'Login',
        'auth.login.button': 'Sign In',
        'auth.register.title': 'Register',
        'auth.register.button': 'Create Account',
        'auth.email': 'Email Address',
        'auth.password': 'Password',
        'auth.confirmPassword': 'Confirm Password',
        'auth.remember': 'Remember me',
        'auth.forgotPassword': 'Forgot password?',
        'auth.loading': 'Please wait...',
        'auth.span.new.user': 'New here? Register now',
        'auth.span.existing.user': 'Already have an account? Sign in',
        'auth.footer.version': 'Version',
        'auth.error.missingFields': 'Please fill out all fields.',
        'auth.error.invalidLogin': 'Email or password is incorrect.',
        'auth.error.invalidRegister': 'Registration failed.',
        'auth.error.passwordMismatch': 'Passwords do not match.',
        'auth.error.sessionKey': 'Invalid session key.',
        'auth.kick.sessionKey': 'Invalid session – please reconnect.',
        'auth.kick.alreadyLoggedIn': 'You are already logged in.',
    },
    de: {
        'auth.login.title': 'Anmeldung',
        'auth.login.button': 'Anmelden',
        'auth.register.title': 'Registrierung',
        'auth.register.button': 'Konto erstellen',
        'auth.email': 'E-Mail-Adresse', 
        'auth.password': 'Passwort',
        'auth.confirmPassword': 'Passwort bestätigen',
        'auth.remember': 'Angemeldet bleiben',
        'auth.forgotPassword': 'Passwort vergessen?',
        'auth.loading': 'Bitte warten...',
        'auth.span.new.user': 'Neu hier? Jetzt registrieren',
        'auth.span.existing.user': 'Du hast bereits ein Konto? Einloggen',
        'auth.footer.version': 'Version',
        'auth.error.missingFields': 'Bitte fülle alle Felder aus.',
        'auth.error.invalidLogin': 'E-Mail oder Passwort ist falsch.',
        'auth.error.invalidRegister': 'Registrierung fehlgeschlagen.',
        'auth.error.passwordMismatch': 'Passwörter stimmen nicht überein.',
        'auth.error.sessionKey': 'Ungültiger Sitzungsschlüssel.',
        'auth.kick.sessionKey': 'Ungültige Sitzung – bitte erneut verbinden.',
        'auth.kick.alreadyLoggedIn': 'Du bist bereits eingeloggt.',
    }
});