import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'character.creator.unable.to.save': 'Unable to save character, rejoin server',
        'character.creator.blemishes': 'Blemishes',
        'character.creator.visibility': 'Visibility',
        'character.creator.sun.damage': 'Sun Damage',
        'character.creator.damage': 'Damage',
        'character.creator.freckles': 'Freckles',
        'character.creator.aging': 'Aging',
        'character.creator.lipstick': 'Lipstick',
        'character.creator.color': 'Color',
        'character.creator.blusher': 'Blusher',
        'character.creator.makeup': 'Makeup',
        'character.creator.blemish': 'Blemish',
        'character.creator.face.father': 'Face Father',
        'character.creator.face.mother': 'Face Mother',
        'character.creator.skin.father': 'Skin Father',
        'character.creator.skin.mother': 'Skin Mother',
        'character.creator.skin.mix': 'Skin Mix',
        'character.creator.face.mix': 'Face Mix',
        'character.creator.eyes': 'Eyes',
        'character.creator.body.type': 'Body Type',
        'character.creator.save': 'Save',
        'character.creator.processing': 'Processing...',
        'character.creator.hair': 'Hair',
        'character.creator.hair.color': 'Hair Color',
        'character.creator.hair.highlight': 'Hair Highlight',
        'character.creator.eyebrows': 'Eyebrows',
        'character.creator.eyebrows.color': 'Eyebrows Color',
        'character.creator.facial.hair': 'Facial Hair',
        'character.creator.facial.color': 'Facial Hair Color',
        'character.creator.category': 'Category',
        'character.creator.nose.width': 'Nose Width',
        'character.creator.nose.height': 'Nose Height',
        'character.creator.nose.length': 'Nose Length',
        'character.creator.nose.profile': 'Nose Profile',
        'character.creator.nose.tip': 'Nose Tip',
        'character.creator.nose.broke': 'Nose Broke',
        'character.creator.brow.height': 'Brow Height',
        'character.creator.brow.depth': 'Brow Depth',
        'character.creator.cheek.height': 'Cheek Height',
        'character.creator.cheek.depth': 'Cheek Depth',
        'character.creator.cheek.puffed': 'Cheek Puffed',
        'character.creator.eyes.size': 'Eyes Size',
        'character.creator.lips.size': 'Lips Size',
        'character.creator.jaw.width': 'Jaw Width',
        'character.creator.jaw.rounded': 'Jaw Round',
        'character.creator.chin.height': 'Chin Height',
        'character.creator.chin.depth': 'Chin Depth',
        'character.creator.chin.pointed': 'Chin Pointed',
        'character.creator.chin.dimple': 'Chin Dimple',
        'character.creator.neck.size': 'Neck Size',
    },
    de: {
        'character.creator.unable.to.save': 'Charakter konnte nicht gespeichert werden, dem Server erneut beitreten',
        'character.creator.blemishes': 'Makel', 
        'character.creator.visibility': 'Sichtbarkeit',
        'character.creator.sun.damage': 'Sonnenschaden',
        'character.creator.damage': 'Schaden',
        'character.creator.freckles': 'Sommerflecken',  
        'character.creator.aging': 'Alterung',
        'character.creator.lipstick': 'Lippenstift',
        'character.creator.color': 'Farbe',
        'character.creator.blusher': 'Rouge',   
        'character.creator.makeup': 'Make-up',
        'character.creator.blemish': 'Makel',
        'character.creator.face.father': 'Gesicht Vater',
        'character.creator.face.mother': 'Gesicht Mutter',
        'character.creator.skin.father': 'Haut Vater',
        'character.creator.skin.mother': 'Haut Mutter',
        'character.creator.skin.mix': 'Haut Mischung',
        'character.creator.face.mix': 'Gesicht Mischung',
        'character.creator.eyes': 'Augen',
        'character.creator.body.type': 'Körpertyp',
        'character.creator.save': 'Speichern',
        'character.creator.processing': 'Verarbeitung...',
        'character.creator.hair': 'Haare',
        'character.creator.hair.color': 'Haarfarbe',
        'character.creator.hair.highlight': 'Haar-Highlight',
        'character.creator.eyebrows': 'Augenbrauen',
        'character.creator.eyebrows.color': 'Augenbrauenfarbe',
        'character.creator.facial.hair': 'Gesichtshaare',
        'character.creator.facial.color': 'Farbe der Gesichtshaare',
        'character.creator.category': 'Kategorie',
        'character.creator.nose.width': 'Nasenbreite',
        'character.creator.nose.height': 'Nasenhöhe',
        'character.creator.nose.length': 'Naselänge',
        'character.creator.nose.profile': 'Nasenprofil',
        'character.creator.nose.tip': 'Nasenspitze',
        'character.creator.nose.broke': 'Nasenbruch',
        'character.creator.brow.height': 'Augenbrauenhöhe',
        'character.creator.brow.depth': 'Augenbrauentiefe',
        'character.creator.cheek.height': 'Wangenhöhe',
        'character.creator.cheek.depth': 'Wangentiefe',
        'character.creator.cheek.puffed': 'Wangen aufgeblasen',
        'character.creator.eyes.size': 'Augengröße',
        'character.creator.lips.size': 'Lippengröße',
        'character.creator.jaw.width': 'Kieferbreite',
        'character.creator.jaw.rounded': 'Kiefer rund',
        'character.creator.chin.height': 'Kinnhöhe',
        'character.creator.chin.depth': 'Kinntiefe',
        'character.creator.chin.pointed': 'Kinnspitze',
        'character.creator.chin.dimple': 'Kinngrübchen',
        'character.creator.neck.size': 'Halsgröße',
    },
});