import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'admin.keyBind.desc': 'Open the admin menu',
        'admin.panel.error': 'Unknown error',
        'admin.panel.noRights': 'No rights to do that',
        'admin.panel.noAccount': 'No account found',
        'admin.panel.noCharacter': 'No character found',
        'admin.panel.noMember': 'No discord member found' ,
        'admin.panel.title': 'Trial Life Roleplay',
        'admin.panel.desc': 'loggedin as',
        'admin.panel.categories': 'Management',
        'admin.panel.logout': 'Sign out',
        'admin.panel.monitoring.title': 'System monitoring',
        'admin.panel.monitoring.cpu': 'CPU (%)',
        'admin.panel.monitoring.ram': 'RAM (%)',
        'admin.panel.monitoring.disk': 'DISK (%)',
        'admin.panel.statistics.title': 'Statistics',
        'admin.panel.statistics.subtitle': 'Server overview and statistics',
        'admin.panel.goto.section': 'To the area',
        'admin.panel.dashboard.settings.title': 'Settings',
        'admin.panel.dashboard.players.title': 'Players',
        'admin.panel.dashboard.vehicles.title': 'Vehicles',
        'admin.panel.dashboard.jobs.title': 'Jobs',
        'admin.panel.dashboard.garages.title': 'Garages',
        'admin.panel.dashboard.shops.title': 'Shops',
        'admin.panel.dashboard.doors.title': 'Doors',
        'admin.panel.dashboard.houses.title': 'Houses, Apartments, Hotels',
        'admin.panel.dashboard.whitelist.title': 'Whitelist-Requests',
        'admin.panel.dashboard.whitelist.desc': 'Review and manage incoming whitelist requests.',
        'admin.panel.dashboard.whitelist.noRequest': 'No open requests',
        'admin.panel.dashboard.whitelist.approve': 'Accept',
        'admin.panel.dashboard.whitelist.reject': 'Reject',
    },
    de: {
        'admin.keyBind.desc': 'Öffne das Admin-Menü',
        'admin.panel.error': 'Unbekannter Fehler',
        'admin.panel.noRights': 'Keine Berechtigung dies zu tun',
        'admin.panel.noAccount': 'Kein Benutzerkonto gefunden',
        'admin.panel.noCharacter': 'Kein Charakter gefunden',
        'admin.panel.noMember': 'Kein Discord-Mitglied gefunden.' ,
        'admin.panel.title': 'Trial Life Roleplay',
        'admin.panel.desc': 'Angemeldet als',
        'admin.panel.categories': 'Verwaltung',
        'admin.panel.logout': 'Abmelden',
        'admin.panel.monitoring.title': 'Systemüberwachung',
        'admin.panel.monitoring.cpu': 'CPU (%)',
        'admin.panel.monitoring.ram': 'RAM (%)',
        'admin.panel.monitoring.disk': 'Festplatte (%)',
        'admin.panel.statistics.title': 'Statistiken',
        'admin.panel.statistics.subtitle': 'Serverübersicht und Statistiken',
        'admin.panel.goto.section': 'Zum Bereich',
        'admin.panel.dashboard.settings.title': 'Einstellungen',
        'admin.panel.dashboard.players.title': 'Spieler',
        'admin.panel.dashboard.vehicles.title': 'Fahrzeuge',
        'admin.panel.dashboard.jobs.title': 'Berufe',
        'admin.panel.dashboard.garages.title': 'Garagen',
        'admin.panel.dashboard.shops.title': 'Geschäfte',
        'admin.panel.dashboard.doors.title': 'Türen',
        'admin.panel.dashboard.houses.title': 'Wohnräume',
        'admin.panel.dashboard.whitelist.title': 'Whitelist-Anfragen',
        'admin.panel.dashboard.whitelist.desc': 'Überprüfe und verwalte eingehende Whitelist-Anfragen.',
        'admin.panel.dashboard.whitelist.noRequests': 'Keine offenen Anfragen',
        'admin.panel.dashboard.whitelist.approve': 'Annehmen',
        'admin.panel.dashboard.whitelist.reject': 'Ablehnen',
    }
});