name = 'Trial Life Roleplay'
host = '0.0.0.0'
port = 7788
players = 20
password = "mgcom2025"
announce = true
token = "9676c313-052a-407a-86ca-f7c9ccdce4f6"
gamemode = 'Roleplay'
website = 'twitch.tv/deathnerotv'
language = 'de'
debug = true
description = 'alt:V Sample Server'
modules = [ 'js-module' ]
resources = [
    'images',
    'fonts',
    'sounds',
    'rmlui',
    'webview',
    'core',
]